package com.wxm.demo.usr

import org.springframework.web.bind.annotation.ResponseBody
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.stereotype.Controller
import org.springframework.web.bind.annotation.RequestMapping

@Controller
@RequestMapping(path = ["/demo"]) // This means URL's start with /demo (after Application path)
class UserController {
    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    private val userRepository: UserRepository? = null

    // This returns a JSON or XML with the users
    val allUsers: Iterable<User>
        @GetMapping(path = ["/all"])
        @ResponseBody
        get() = userRepository!!.findAll()

    @GetMapping(path = ["/add"]) // Map ONLY GET Requests
    @ResponseBody
    fun addNewUser(@RequestParam name: String, @RequestParam email: String): String {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        val n = User()
        n.name = name
        n.email = email
        userRepository!!.save(n)
        return "Saved"
    }
}